application: tomatopanic
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /(.*\.(css))$
  static_files: css/\1
  upload: css/.*\.(css)$
  
- url: /stylesheets
  static_dir: css

- url: /(.*\.(gif|png|jpg))$
  static_files: img/\1
  upload: img/.*\.(gif|png|jpg)$

- url: /.*
  script: 404.php